Ayudante/urls.py
from django.urls import path
from . import views

app_name='Ayudante'

urlpatterns=[
    path('enviar_codigo/', views.enviar_codigo, name="enviar_codigo"),
    path('vista_ayudante/', views.vista_ayudante, name="vista_ayudante"),
    path('trueques_filial/', views.ver_trueques_filial, name="Ver_Trueques_filial"),
    path('validar_ticket/', views.validar_ticket_usuario, name="Validar_ticket_usuario"),
    path('validar_codigo_trueque/', views.validar_codigo_trueque, name='validar_codigo_trueque'),
    path('permitir_trueque/', views.permitir_trueque, name='permitir_trueque'),
]

Caridas/urls.py
from django.contrib import admin
from django.urls import path,include
from administrador import views as admin_views
from django.conf import settings
from django.conf.urls.static import static

#urls que los clientes pueden visitar
urlpatterns = [
    path('admin/', admin.site.urls), #aca en vez de llamar a admin.site.urls podria llamar al html correspondiente 
    path('productos/', include('Productos.urls')),
    path('filiales/', include('Filiales.urls')),    
    path('accounts/', include('accounts.urls')),  
    path('', include('Pantalla_principal.urls')),
    path('administrador/', include('administrador.urls')),
    path('ayudante/', include('Ayudante.urls')),
    path('usuario/', include('Usuario.urls')),
    path('busqueda/', include('busqueda.urls')),
    path('Intercambiar_puntos/', include('Intercambiar_puntos.urls')),
    path('Trueques/', include('Trueques.urls')),
    path('Noticias/', include('Noticias.urls')),
    path('Reseñas/', include('Reseñas.urls')),
    path('Donaciones/', include('Donaciones.urls')),
    path('Estadisticas/', include('Estadisticas.urls')),
]

handler404 = admin_views.error404
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Filiales/urls.py
from django.urls import path
from . import views

app_name = 'Filiales'
app_name = 'Filiales'

urlpatterns = [
    path('create_filial/', views.create_filial, name="create_filial"),
    path('list_filiales/', views.list_filiales, name="list_filiales"),
    path('modify_filial/', views.modify_filial, name="modify_filial"),
    path('set_filial_id/<int:filial_id>/', views.set_filial_id, name="set_filial_id"),
    path('ver_datos_filiales/', views.ver_datos_filiales, name='ver_datos_filiales'),
    path('select_filial/', views.select_filial, name="select_filial"),
]

Usuario/urls.py
from django.urls import path
from . import views

app_name='Usuario' #esto es necesario para que dps cuando va a reest. contraseña o reg. usuario, siga el link apropiado

#urls que los clientes pueden visitar
urlpatterns = [
    path('opciones_trueque/', views.opciones_trueque,name="opciones_trueque"),
    path('productos/', views.show_productos, name='show_productos_usuario'),
    path('trueques/', views.show_trueques, name='show_trueques_usuario'),
    path('opciones_trueque/', views.opciones_trueque, name='opciones_trueque'),
    
]

accounts/urls.py
from django.urls import path
from . import views

app_name='accounts' #esto es necesario para que dps cuando va a reest. contraseña o reg. usuario, siga el link apropiado

urlpatterns=[
    path('login/', views.signin, name='login'),

    path('reestablecer_contrasena/', views.reestablecer_contrasena,name="reestablecer_contrasena"),
    path('verificar_codigo/', views.verificar_codigo, name='verificar_codigo'),
    path('cambiar_contrasena/',views.cambiar_contrasena,name='cambiar_contraseña'),

    path('registrar_usuario/', views.registrar_usuario,name="registrar_usuario"),
    
    path('login/logout', views.cerrar_sesion, name='logout'),
    path('editar_perfil/', views.editar_perfil, name='editar_perfil'),
    ]

Caridas/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head> 
        <meta charset="utf-8"/> 
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> CariDas </title>
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'styles/mainBase.css' %}">
    </head>
    <body>
        <hr class="LineaHorizontal">
        <nav>
            <ul>
                <li><a href="{% url 'Pantalla_principal:Pantalla_principal' %}"><img id="LogoCaritas" src="{% static 'LogoCaritasRectangular.png' %}" alt="logo_caritas"></a></li>
                <li><a href="{% url 'Filiales:list_filiales' %}" class="Navegation"> Filiales </a></li>
                <li><a href="{% url 'Usuario:opciones_trueque' %}" class="Navegation"> Trueques </a></li>
                <li><a href="{% url 'Donaciones:donar' %}" class="Navegation"> Donaciones </a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'Pantalla_principal:listar_notificaciones' %}" class="notification-icon">
                    <img src="{% static 'campana.png' %}" alt="Notificaciones">
                    {% if notificaciones_no_leidas > 0 %}
                        <span class="badge badge-primary">{{ notificaciones_no_leidas }}</span>
                    {% endif %}
                </a></li>
                {% endif %}
                </a></li>
                {% if user.is_authenticated %}
                    {% if user.id == 1 %}
                        <li><a href="{% url 'vista_admin' %}"><img id="LogoUsuario" src="{% static 'logo_caritas.png' %}"> </a></li>
                    {% elif user.is_ayudante %}
                        <li><a href="{% url 'Ayudante:vista_ayudante' %}"><img id="LogoUsuario" src="{% static 'logo_caritas.png' %}"> </a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:editar_perfil' %}"><img id="LogoUsuario" src="{% if user.profile_picture %}{% static user.profile_picture %}{% else %}{% static 'usuarioDefault.png' %}{% endif %}"> </a></li>
                    {% endif %}
                    <li><a href="{% url 'accounts:logout' %}"  id="Cerrar-Sesion"> Cerrar Sesión </a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}" id="Acceder">Acceder</a></li>
                {% endif %}
            </ul>
        </nav>
        <hr class="LineaHorizontal">

    {% block content %}
    {% endblock %}

</body>

</html>