Ayudante/urls.py
from django.urls import path
from . import views

app_name='Ayudante'

urlpatterns=[
    path('enviar_codigo/', views.enviar_codigo, name="enviar_codigo"),
    path('vista_ayudante/', views.vista_ayudante, name="vista_ayudante"),
    path('trueques_filial/', views.ver_trueques_filial, name="Ver_Trueques_filial"),
    path('validar_ticket/', views.validar_ticket_usuario, name="Validar_ticket_usuario"),
    path('validar_codigo_trueque/', views.validar_codigo_trueque, name='validar_codigo_trueque'),
    path('permitir_trueque/', views.permitir_trueque, name='permitir_trueque'),
]

Caridas/urls.py
from django.contrib import admin
from django.urls import path,include
from administrador import views as admin_views
from django.conf import settings
from django.conf.urls.static import static

#urls que los clientes pueden visitar
urlpatterns = [
    path('admin/', admin.site.urls), #aca en vez de llamar a admin.site.urls podria llamar al html correspondiente 
    path('productos/', include('Productos.urls')),
    path('filiales/', include('Filiales.urls')),    
    path('accounts/', include('accounts.urls')),  
    path('', include('Pantalla_principal.urls')),
    path('administrador/', include('administrador.urls')),
    path('ayudante/', include('Ayudante.urls')),
    path('usuario/', include('Usuario.urls')),
    path('busqueda/', include('busqueda.urls')),
    path('Intercambiar_puntos/', include('Intercambiar_puntos.urls')),
    path('Trueques/', include('Trueques.urls')),
    path('Noticias/', include('Noticias.urls')),
    path('Reseñas/', include('Reseñas.urls')),
    path('Donaciones/', include('Donaciones.urls')),
    path('Estadisticas/', include('Estadisticas.urls')),
]

handler404 = admin_views.error404
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Reseñas/urls.py
from django.urls import path
from . import views

app_name = 'Reseñas'

urlpatterns = [
    path('add_review/<int:trade_id>/', views.add_review, name='add_review'),
]

Trueques/urls.py
from django.urls import path
from . import views

app_name = 'Trueques'

urlpatterns = [
    path('registro_trueque/', views.registro_trueque, name='registro_trueque'),
    path('trueques_aceptados/', views.trueques_en_espera_de_confirmacion, name='ver_trueques_en_espera_de_confirmacion'),
    path('ofertar_producto/', views.ofertar_producto, name='ofertar_producto'),
    path('almacenar_trueque/<int:trueque_id>/', views.almacenar_trueque_id, name='almacenar_trueque'),
    path('procesar_oferta/', views.procesar_oferta, name='procesar_oferta'),
    path('cancelar_trueque/<int:trueque_id>/', views.cancelar_trueque, name='cancelar_trueque'),
]

Usuario/urls.py
from django.urls import path
from . import views

app_name='Usuario' #esto es necesario para que dps cuando va a reest. contraseña o reg. usuario, siga el link apropiado

#urls que los clientes pueden visitar
urlpatterns = [
    path('opciones_trueque/', views.opciones_trueque,name="opciones_trueque"),
    path('productos/', views.show_productos, name='show_productos_usuario'),
    path('trueques/', views.show_trueques, name='show_trueques_usuario'),
    path('opciones_trueque/', views.opciones_trueque, name='opciones_trueque'),
    
]

busqueda/urls.py
from django.urls import path
from . import views

app_name='busqueda'

urlpatterns = [
    path('trueques_usuarios/', views.listar_trueques, name='listar_Trueques'),
]

Usuario/models.py
from django.db import models

# Create your models here.

Usuario/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from Productos.models import Producto
from django.db.models import Q
from Trueques.models import Trueque,IntercambioTrueque
from Productos.models import Producto
from django.db.models import Q
from Trueques.models import Trueque,IntercambioTrueque
from Reseñas.models import Review
from Trueques.models import Trueque
from Pantalla_principal.models import Notificacion
@login_required
def opciones_trueque(request):
    return render(request, 'selectUsuario.html') 

@login_required
def show_productos(request):
    productos = Producto.objects.filter(usuario=request.user, borrado=False)
    if request.method == 'POST':
        producto_id = request.POST.get('producto_id')
        try:
            product = Producto.objects.get(id=producto_id, usuario=request.user)
            product.borrado = True
            product.save()

            trueques_relacionados = Trueque.objects.filter(producto=product)
            for trueque in trueques_relacionados:
                trueque.estado_trueque = 'Eliminado'
                trueque.save()
                
                # Crear notificación para el usuario del trueque
                mensaje_trueque = f"Tu trueque '{trueque.titulo}' ha sido eliminado."
                notificacion_trueque = Notificacion(usuario=trueque.usuario, mensaje=mensaje_trueque)
                notificacion_trueque.save()

                # Notifica en el caso de que el dueño del truque ofertó y luego lo eliminó
                intercambios = IntercambioTrueque.objects.filter(Q(trueque_1=trueque))
                for intercambio in intercambios:
                    intercambio.estado = 'Eliminado'
                    intercambio.save()

                    if intercambio.producto_2.usuario != trueque.usuario:
                        mensaje_producto = f"Tu solicitud para el trueque '{trueque.titulo}' ha sido eliminada porque el producto fue eliminado."
                        notificacion_producto = Notificacion(usuario=intercambio.producto_2.usuario, mensaje=mensaje_producto)
                        notificacion_producto.save()


            # Notifica en el caso de que un usuario hay ofertedo y luego elimando el producto
            intercambios = IntercambioTrueque.objects.filter(Q(producto_2__id=product.id), estado = "Espera de confirmacion")
            for intercambio in intercambios:
                intercambio.estado = 'Eliminado'
                intercambio.save()

                mensaje_producto = f"Tu solicitud para el trueque '{intercambio.trueque_1.titulo}' ha sido eliminada porque el producto fue eliminado."
                notificacion_producto = Notificacion(usuario=intercambio.producto_2.usuario, mensaje=mensaje_producto)
                notificacion_producto.save()

                mensaje_trueque_usuario = f"Una solicitud de intercambio relacionada a tu trueque '{intercambio.trueque_1.titulo}' ha sido eliminado."
                notificacion_trueque_usuario = Notificacion(usuario=intercambio.trueque_1.usuario, mensaje=mensaje_trueque_usuario)
                notificacion_trueque_usuario.save()

        except Producto.DoesNotExist:
            return render(request, 'show_productos_usuario.html', {'productos': productos, 'error_message': 'Producto eliminado'})
    
    return render(request, 'show_productos_usuario.html', {'productos': productos})

@login_required
def show_trueques  (request):
    user_id = request.user.id
    #trueques = Trueque.objects.filter(usuario_id=request.user.id).exclude(estado_trueque='Eliminado')
    trueques_aceptados = IntercambioTrueque.objects.filter(
    Q(trueque_1__usuario_id=request.user.id) | Q(producto_2__usuario_id=request.user.id),
    estado='Aceptado'
    )
    #trueques_cancelados = IntercambioTrueque.objects.filter(Q(trueque_1__usuario_id=request.user.id) | Q(producto_2__usuario_id=request.user.id), estado='Rechazado')
    trueques_cancelados_creador = IntercambioTrueque.objects.filter(
        trueque_1__usuario_id=request.user.id, estado='Rechazado'
    )
    trueques_cancelados_ofertante = IntercambioTrueque.objects.filter(
        producto_2__usuario_id=request.user.id, estado='Rechazado'
    )
    trueques_pendientes = Trueque.objects.filter(usuario_id = request.user.id, estado_trueque='Pendiente')
    trueques_espera_de_confirmacion = IntercambioTrueque.objects.filter(trueque_1__usuario_id=request.user.id, estado='Espera de confirmacion').count()
    trueques_completados = IntercambioTrueque.objects.filter(
    Q(trueque_1__usuario_id=request.user.id) | Q(producto_2__usuario_id=request.user.id),
    estado='Completado'
    )

    # Obtener las reseñas realizadas
    reseñas_realizadas = Review.objects.filter(user_id=user_id).values_list('trade_id', flat=True)
    #aca esta la eliminacion del trueque
    if request.method == 'POST':
        trueque_id = request.POST.get('trueque_id')
        #asad
        try:
            trueque = Trueque.objects.get(id=trueque_id, usuario=request.user)
            trueque.estado_trueque = 'Eliminado' 
            trueque.save()

            # Crear notificación para el usuario del trueque
            mensaje_trueque = f"Tu trueque '{trueque.titulo}' ha sido eliminado."
            notificacion_trueque = Notificacion(usuario=trueque.usuario, mensaje=mensaje_trueque)
            notificacion_trueque.save()

            # Crear notificación para el usuario del producto si es diferente
            intercambios = IntercambioTrueque.objects.filter(producto_2__id=trueque.producto.id, producto_2__borrado= False)
            for intercambio in intercambios:
                if intercambio.producto_2.usuario != trueque.usuario:
                    mensaje_producto = f"El trueque al que solicitaste con tu producto '{intercambio.producto_2.titulo}' ha sido eliminado."
                    notificacion_producto = Notificacion(usuario=intercambio.producto_2.usuario, mensaje=mensaje_producto)
                    notificacion_producto.save()


        except Trueque.DoesNotExist:
            return render(request, 'show_trueques_usuario.html', {'error_message': 'Trueque eliminado','trueques_aceptados':trueques_aceptados.count()})
    
    context = {
        'trueques_aceptados': trueques_aceptados,
        'trueques_cancelados_creador': trueques_cancelados_creador,
        'trueques_cancelados_ofertante': trueques_cancelados_ofertante,
        'trueques_pendientes': trueques_pendientes,
        'trueques_en_espera_de_confirmacion': trueques_espera_de_confirmacion,
        'trueques_completados':trueques_completados,
        'reseñas_realizadas': reseñas_realizadas
    }
    return render(request, 'show_trueques_usuario.html', context)

Usuario/templates/confirm_delete.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<h1>Eliminar Producto</h1>
<p>¿Estás seguro de que deseas eliminar el producto "{{ product.titulo }}"?</p>
<form method="post" action="{% url 'Usuario:show_productos_usuario' %}">
    {% csrf_token %}
    <input type="hidden" name="producto_id" value="{{ product.id }}">
    <button type="submit" name="confirm" class="btn btn-danger">Sí, eliminar</button>
    <a href="{% url 'Usuario:show_productos_usuario' %}" class="btn btn-secondary">Cancelar</a>
</form>
{% endblock %}

Usuario/templates/selectUsuario.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'styles/select.css' %}">
<title>Lista Vertical</title>



<div class="container">
    {% if not request.user.is_ayudante %}
    <div class="sidebar">
        <ul>
            <li><a href="{% url 'Usuario:show_productos_usuario' %}" class="Navegation"> Mis Productos </a></li>
            <li><a href="{% url 'Usuario:show_trueques_usuario' %}" class="Navegation"> Mis Trueques </a></li>
            <li><a href="{% url 'busqueda:listar_Trueques' %}" class="Navegation"> Buscar Trueques </a></li>
            <li><a href="{% url 'Intercambiar_puntos:seleccionar_categoria' %}" class="Navegation"> Intercambiar Puntos </a></li>
            <li><a href="{% url 'Pantalla_principal:Pantalla_principal' %}"> Volver </a></li>
        </ul>
    </div>
    <div class="linea-vertical"></div>
    {% else %}
        <div class="sidebar">
            <ul>
                <li><a href="{% url 'Ayudante:Ver_Trueques_filial' %}" class="Navegation"> Ver Trueques Filial </a></li>
                <li><a href="{% url 'Ayudante:Validar_ticket_usuario' %}" class="Navegation"> Validar Ticket usuario </a></li>
                <li><a href="{% url 'Ayudante:validar_codigo_trueque' %}" class="Navegation active">Validar Código Trueque</a></li>
                <li><a href="{% url 'Pantalla_principal:Pantalla_principal' %}"> Volver </a></li>
            </ul>
        </div>
        <div class="linea-vertical"></div>
    {% endif %}
</div>



{% endblock %}

Usuario/templates/show_productos_usuario.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'styles/select.css' %}">
<div class="container">
    <div class="sidebar">
        <ul>
            <li><a href="{% url 'Usuario:show_productos_usuario' %}" class="Navegation"> Mis Productos </a></li>
            <li><a href="{% url 'Usuario:show_trueques_usuario' %}" class="Navegation"> Mis Trueques </a></li>
            <li><a href="{% url 'busqueda:listar_Trueques' %}" class="Navegation"> Buscar Trueques </a></li>
            <li><a href="{% url 'Intercambiar_puntos:seleccionar_categoria' %}" class="Navegation"> Intercambiar Puntos </a></li>
            <li><a href="{% url 'Pantalla_principal:Pantalla_principal' %}"> Volver </a></li>
        </ul>
    </div>
    <div class="linea-vertical"></div>
    <div class="contenido">
        <h1>Lista de Productos</h1>

        <table>
            <thead>
                <tr>
                    <th>Título</th>
                    <th>Descripción</th>
                    <th>Estado</th>
                    <th>Categoría</th>
                    <th>Foto</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in productos %}
                <tr>
                    <td>{{ producto.titulo }}</td>
                    <td>{{ producto.descripcion }}</td>
                    <td>{{ producto.estado }}</td>
                    <td>{{ producto.categoria }}</td>
                    <td>
                        <img src="{% static producto.foto_producto.url %}" alt="{{ producto.titulo }}" style="width: 100px; height: auto;">
                    </td>
                    <td>
                        <form method="post" action="{% url 'Usuario:show_productos_usuario' %}" style="display:inline;">
                            {% csrf_token %}
                            <input type="hidden" name="producto_id" value="{{ producto.id }}">
                            <button type="submit" class="btn btn-danger" onclick="return confirmDelete()">Eliminar</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <!-- Botón para agregar nuevo producto -->
        <div>
            <a href="{% url 'Productos:create_product' %}" class="btn-custom">Agregar Producto</a>
        </div>
    </div>
</div>

<script>
    function confirmDelete() {
        return confirm('¿Estás seguro de que deseas eliminar este producto?');
    }
</script>

{% endblock %}

Usuario/templates/show_trueques_usuario.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'styles/select.css' %}">
    {% csrf_token %}
<div class="container">
    <div class="sidebar">
        <ul>
            <li><a href="{% url 'Usuario:show_productos_usuario' %}" class="Navegation"> Mis Productos </a></li>
            <li><a href="{% url 'Usuario:show_trueques_usuario' %}" class="Navegation"> Mis Trueques </a></li>
            <li><a href="{% url 'busqueda:listar_Trueques' %}" class="Navegation"> Buscar Trueques </a></li>
            <li><a href="{% url 'Intercambiar_puntos:seleccionar_categoria' %}" class="Navegation"> Intercambiar Puntos </a></li>
            <li><a href="{% url 'Pantalla_principal:Pantalla_principal' %}"> Volver </a></li>
        </ul>
    </div>
    <div class="linea-vertical"></div>
    <div class="contenido">
        <h1>Lista de Trueques</h1>
        <div>
            <a href="{% url 'Trueques:registro_trueque' %}" class="btn-custom">Agregar Trueque</a>
        </div>
        <h4><a href="{% url 'Trueques:ver_trueques_en_espera_de_confirmacion' %}">Trueques Aceptados({{ trueques_en_espera_de_confirmacion }})</a></h4>
    
        <div class="tab-content">
            {% if messages %}
            <ul class="messages" style="list-style: none;">
                {% for message in messages %}
                <b>
                    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                </b>
                {% endfor %}
            </ul>
            {% endif %}
            <div class="tab-pane fade show active" id="pendientes">
                <h2>Trueques Pendientes</h2>
                <table>
                    {% if trueques_pendientes %}
                    {% if trueques_pendientes %}
                    <thead>
                        <tr>
                            <th>Título</th>
                            <th>Producto</th>
                            <th>Descripcion</th>
                            <th>Estado del Producto</th>
                            <th>Foto Del Producto</th>
                            <th>Acción</th>

                        </tr>
                    </thead>
                    {% endif %}
                    {% endif %}
                    <tbody>
                        {% for trueque in trueques_pendientes %}
                            <tr>
                                <td>{{ trueque.titulo }}</td>
                                <td>{{ trueque.producto }}</td>
                                <td>{{ trueque.descripcion }}</td>
                                <td>{{ trueque.estado }}</td>
                                <td>
                                    <img src="{% static 'media/' %}{{ trueque.foto_producto }}" alt="{{ trueque.titulo }}" style="width: 100px; height: auto;">
                                </td>
                                <td>{{ trueque.estado_trueque }}</td>
                                <td>
                                    <form method="post" action="{% url 'Usuario:show_trueques_usuario' %}" style="display:inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="trueque_id" value="{{ trueque.id }}">
                                        <button type="submit" class="btn btn-danger">Eliminar</button>
                                    </form>
                                </td>
                            </tr>
                        {% empty %}
                            <p>No hay trueques Pendientes.</p>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <h2>Trueques Completados</h2>
            <table>
                {% if trueques_completados %}
                <thead>
                    <tr>
                        <th>Título</th>
                        <th>Producto</th>
                        <th>Descripcion</th>
                        <th>Estado del Producto</th>
                        <th>Foto Del Producto</th>
                        <th>Estado del trueque</th>
                    </tr>
                </thead>
                {% endif %}
                <tbody>
                    {% for trueque in trueques_completados %}
                    <tr>
                        <td>{{ trueque.trueque_1.titulo }}</td>
                        <td>{{ trueque.trueque_1.producto }}</td>
                        <td>{{ trueque.trueque_1.descripcion }}</td>
                        <td>{{ trueque.trueque_1.estado }}</td>
                        <td>
                            <img src="{% static 'media/' %}{{ trueque.trueque_1.foto_producto }}"
                                alt="{{ trueque.trueque_1.titulo }}" style="width: 100px; height: auto;">
                        </td>
                        <td>{{ trueque.trueque_1.estado_trueque }}</td>
                        {% if trueque.id not in reseñas_realizadas %}
                            <td>
                                <form method="post" action="{% url 'Reseñas:add_review' trueque.trueque_1.id %}"
                                    style="display:inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="trueque_id" value="{{ trueque.trueque_1.id }}">
                                    <button type="submit" class="btn btn-danger">Dejar Reseña</button>
                                </form>
                            </td>
                        {% endif %}
                    </tr>
                    {% empty %}
                    <p>No hay trueques completados.</p>
                    {% endfor %}
                </tbody>
            </table>

            <div class="tab-pane fade" id="aceptados">
                <h2>Trueques Aceptados</h2>
                <table>
                    {% if trueques_aceptados %}
                    {% if trueques_aceptados %}
                    <thead>
                        <tr>
                            <th>Título</th>
                            <th>Producto</th>
                            <th>Descripcion</th>
                            <th>Estado del Producto</th>
                            <th>Foto Del Producto</th>

                        </tr>
                    </thead>
                    {% endif %}
                    {% endif %}
                    <tbody>
                        {% for trueque in trueques_aceptados %}
                        <tr>
                            <td>{{ trueque.trueque_1.titulo }}</td>
                            <td>{{ trueque.trueque_1.producto }}</td>
                            <td>{{ trueque.trueque_1.descripcion }}</td>
                            <td>{{ trueque.trueque_1.estado }}</td>
                            <td>
                                <img src="{% static 'media/' %}{{ trueque.trueque_1.foto_producto }}"
                                    alt="{{ trueque.trueque_1.titulo }}" style="width: 100px; height: auto;">
                            </td>
                        </tr>
                        {% empty %}
                        <p>No hay trueques Aceptados.</p>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="tab-content">
                <div class="tab-pane fade" id="cancelados">
                    <h2>Trueques Cancelados</h2>

                    <h3>Como Creador</h3>
                    <table>
                        {% if trueques_cancelados_creador %}
                        <thead>
                            <tr>
                                <th>Título</th>
                                <th>Producto</th>
                                <th>Descripcion</th>
                                <th>Foto Del Producto</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        {% endif %}
                        <tbody>
                            {% for trueque in trueques_cancelados_creador %}
                            <tr>
                                <td>{{ trueque.trueque_1.titulo }}</td>
                                <td>{{ trueque.trueque_1.producto }}</td>
                                <td>{{ trueque.trueque_1.descripcion }}</td>
                                <td>
                                    <img src="{% static 'media/' %}{{ trueque.trueque_1.foto_producto }}"
                                        alt="{{ trueque.trueque_1.titulo }}" style="width: 100px; height: auto;">
                                </td>
                                {% if trueque.id not in reseñas_realizadas %}
                                    {% if trueque.fue_trueque %}
                                    <td>
                                        <form method="post" action="{% url 'Reseñas:add_review' trueque.trueque_1.id %}" style="display:inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="trueque_id" value="{{ trueque.trueque_1.id }}">
                                            <button type="submit" class="btn btn-danger">Dejar Reseña</button>
                                        </form>
                                    </td>
                                    {% endif %}
                                {% endif %}
                            </tr>
                            {% empty %}
                            <p>No hay trueques cancelados como creador.</p>
                            {% endfor %}
                        </tbody>
                    </table>

                    <h3>Como Ofertante</h3>
                    <table>
                        {% if trueques_cancelados_ofertante %}
                        <thead>
                            <tr>
                                <th>Título</th>
                                <th>Producto</th>
                                <th>Descripcion</th>
                                <th>Foto Del Producto</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        {% endif %}
                        <tbody>
                            {% for trueque in trueques_cancelados_ofertante %}
                            <tr>
                                <td>{{ trueque.producto_2.titulo }}</td>
                                <td>{{ trueque.producto_2.producto }}</td>
                                <td>{{ trueque.producto_2.descripcion }}</td>
                                <td>
                                    <img src="{% static 'media/' %}{{ trueque.producto_2.foto_producto }}"
                                        alt="{{ trueque.producto_2.titulo }}" style="width: 100px; height: auto;">
                                </td>
                                {% if trueque.id not in reseñas_realizadas %}
                                    {% if trueque.fue_producto %}
                                        <td>
                                            <form method="post" action="{% url 'Reseñas:add_review' trueque.trueque_1.id %}"
                                                style="display:inline;">
                                                {% csrf_token %}
                                                <input type="hidden" name="trueque_id" value="{{ trueque.trueque_1.id }}">
                                                <button type="submit" class="btn btn-danger">Dejar Reseña</button>
                                            </form>
                                        </td>
                                    {% endif %}
                                {% endif %}
                            </tr>
                            {% empty %}
                            <p>No hay trueques cancelados como ofertante.</p>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
    {% endblock %}