Caridas/urls.py
from django.contrib import admin
from django.urls import path,include
from administrador import views as admin_views
from django.conf import settings
from django.conf.urls.static import static

#urls que los clientes pueden visitar
urlpatterns = [
    path('admin/', admin.site.urls), #aca en vez de llamar a admin.site.urls podria llamar al html correspondiente 
    path('productos/', include('Productos.urls')),
    path('filiales/', include('Filiales.urls')),    
    path('accounts/', include('accounts.urls')),  
    path('', include('Pantalla_principal.urls')),
    path('administrador/', include('administrador.urls')),
    path('ayudante/', include('Ayudante.urls')),
    path('usuario/', include('Usuario.urls')),
    path('busqueda/', include('busqueda.urls')),
    path('Intercambiar_puntos/', include('Intercambiar_puntos.urls')),
    path('Trueques/', include('Trueques.urls')),
    path('Noticias/', include('Noticias.urls')),
    path('Reseñas/', include('Reseñas.urls')),
    path('Donaciones/', include('Donaciones.urls')),
    path('Estadisticas/', include('Estadisticas.urls')),
]

handler404 = admin_views.error404
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Intercambiar_puntos/urls.py
from django.urls import path
from . import views

app_name='Intercambiar_puntos' 

urlpatterns=[
    path('seleccionar_categoria/', views.seleccionar_categoria, name='seleccionar_categoria'),
]

Pantalla_principal/urls.py
from django.urls import path
from . import views

app_name='Pantalla_principal' #esto es necesario para que dps cuando va a reest. contraseña o reg. usuario, siga el link apropiado

#urls que los clientes pueden visitar
urlpatterns = [
    path('', views.pantalla_principal,name="Pantalla_principal"),
    path('listar_notificaciones/', views.listar_notificaciones, name='listar_notificaciones'),
    path('delete_notificacion/', views.delete_notificacion, name='delete_notificacion'),
    path('donaciones/', views.donaciones,name="Donaciones"),
]

Trueques/urls.py
from django.urls import path
from . import views

app_name = 'Trueques'

urlpatterns = [
    path('registro_trueque/', views.registro_trueque, name='registro_trueque'),
    path('trueques_aceptados/', views.trueques_en_espera_de_confirmacion, name='ver_trueques_en_espera_de_confirmacion'),
    path('ofertar_producto/', views.ofertar_producto, name='ofertar_producto'),
    path('almacenar_trueque/<int:trueque_id>/', views.almacenar_trueque_id, name='almacenar_trueque'),
    path('procesar_oferta/', views.procesar_oferta, name='procesar_oferta'),
    path('cancelar_trueque/<int:trueque_id>/', views.cancelar_trueque, name='cancelar_trueque'),
]

Usuario/urls.py
from django.urls import path
from . import views

app_name='Usuario' #esto es necesario para que dps cuando va a reest. contraseña o reg. usuario, siga el link apropiado

#urls que los clientes pueden visitar
urlpatterns = [
    path('opciones_trueque/', views.opciones_trueque,name="opciones_trueque"),
    path('productos/', views.show_productos, name='show_productos_usuario'),
    path('trueques/', views.show_trueques, name='show_trueques_usuario'),
    path('opciones_trueque/', views.opciones_trueque, name='opciones_trueque'),
    
]

busqueda/urls.py
from django.urls import path
from . import views

app_name='busqueda'

urlpatterns = [
    path('trueques_usuarios/', views.listar_trueques, name='listar_Trueques'),
]

busqueda/models.py
from django.db import models

# Create your models here.

busqueda/views.py
from django.shortcuts import render
from Productos.models import Categoria
from Trueques.models import Trueque
from django.contrib.auth.decorators import login_required
from django.db.models import Q

@login_required
def listar_trueques(request):
    estado = request.GET.get('estado')
    categoria_id = request.GET.get('categoria')
    query = request.GET.get('q')
    user = request.user


    trueques = Trueque.objects.select_related('producto', 'producto__categoria').filter(~Q(producto__usuario=user), estado_trueque='Pendiente')


    if estado:
        trueques = trueques.filter(estado=estado)

    if categoria_id:
        trueques = trueques.filter(producto__categoria_id=categoria_id) 

    if query:
        trueques = trueques.filter(Q(titulo__icontains=query) | Q(descripcion__icontains=query))

    categorias = Categoria.objects.filter(borrado=False)


    context = {
        'trueques': trueques,
        'estado': estado,
        'categorias': categorias,
        'categoria_id': categoria_id,
        'query': query,
    }

    return render(request, 'listar_Trueques.html', context)

busqueda/templates/listar_Trueques.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'listar_Trueques.css' %}">
<div class="container">
    <div class="sidebar">
        <ul>
            <li><a href="{% url 'Usuario:show_productos_usuario' %}" class="Navegation"> Mis Productos </a></li>
            <li><a href="{% url 'Usuario:show_trueques_usuario' %}" class="Navegation"> Mis Trueques </a></li>
            <li><a href="{% url 'busqueda:listar_Trueques' %}" class="Navegation"> Buscar Trueques </a></li>
            <li><a href="{% url 'Intercambiar_puntos:seleccionar_categoria' %}" class="Navegation"> Intercambiar Puntos </a></li>
            <li><a href="{% url 'Pantalla_principal:Pantalla_principal' %}"> Volver </a></li>
        </ul>
    </div>
    <div class="linea-vertical"></div>
    <div class="contenido">
        <h1>Lista de Trueques Disponibles</h1>
        <form method="get" action="{% url 'busqueda:listar_Trueques' %}">
            <label for="q">Buscar:</label>
            <input type="text" id="q" name="q" value="{{ query|default:'' }}"
                placeholder="Buscar por título o descripción">
            <button type="submit">Buscar</button>
        </form>

        <form method="get" action="{% url 'busqueda:listar_Trueques' %}">
            <label for="estado">Estado:</label>
            <select name="estado" id="estado">
                <option value="" {% if not estado %}selected{% endif %}>Todos</option>
                <option value="nuevo" {% if estado == "nuevo" %}selected{% endif %}>Nuevo</option>
                <option value="usado - como nuevo" {% if estado == "usado - como nuevo" %}selected{% endif %}>Usado - Como
                    nuevo</option>
                <option value="usado - muy bueno" {% if estado == "usado - muy bueno" %}selected{% endif %}>Usado - Muy
                    bueno</option>
                <option value="usado - bueno" {% if estado == "usado - bueno" %}selected{% endif %}>Usado - Bueno</option>
                <option value="usado - aceptable" {% if estado == "usado - aceptable" %}selected{% endif %}>Usado -
                    Aceptable</option>
            </select>

            <label for="categoria">Categoría:</label>
            <select name="categoria" id="categoria">
                <option value="" {% if not categoria_id %}selected{% endif %}>Todas</option>
                {% for categoria in categorias %}
                <option value="{{ categoria.id }}" {% if categoria.id|stringformat:"s" == categoria_id %}selected{% endif %}>{{ categoria.nombre }}</option>
                {% endfor %}
            </select>

            <button type="submit">Filtrar</button>
            <a href="{% url 'busqueda:listar_Trueques' %}">
                <button type="button">Eliminar filtros</button>
            </a>
        </form>


        <div class="contenido2">
            {% if trueques %}
            <table>
                <thead>
                    <tr>
                        <th>Título</th>
                        <th>Descripción</th>
                        <th>Categoría del Producto</th>
                        <th>Foto</th>
                        <th>Estado</th>
                        <th>Acción</th>
                    </tr>
                </thead>
                <tbody>
                    {% for trueque in trueques %}
                        <tr>
                            <td>{{ trueque.titulo }}</td>
                            <td>{{ trueque.descripcion }}</td>
                            <td>{{ trueque.producto.categoria.nombre }}</td>
                            <td>
                                <img src="{{ trueque.foto_producto.url }}" alt="{{ trueque.titulo }}" style="width: 100px; height: auto;">
                            </td>
                            <td>{{ trueque.get_estado_display }}</td>
                            <td><a href="{% url 'Trueques:almacenar_trueque' trueque.id %}">Ofertar producto</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p style="color: red;">No hay trueques que cumplan lo pedido.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}