Caridas/urls.py
from django.contrib import admin
from django.urls import path,include
from administrador import views as admin_views
from django.conf import settings
from django.conf.urls.static import static

#urls que los clientes pueden visitar
urlpatterns = [
    path('admin/', admin.site.urls), #aca en vez de llamar a admin.site.urls podria llamar al html correspondiente 
    path('productos/', include('Productos.urls')),
    path('filiales/', include('Filiales.urls')),    
    path('accounts/', include('accounts.urls')),  
    path('', include('Pantalla_principal.urls')),
    path('administrador/', include('administrador.urls')),
    path('ayudante/', include('Ayudante.urls')),
    path('usuario/', include('Usuario.urls')),
    path('busqueda/', include('busqueda.urls')),
    path('Intercambiar_puntos/', include('Intercambiar_puntos.urls')),
    path('Trueques/', include('Trueques.urls')),
    path('Noticias/', include('Noticias.urls')),
    path('Reseñas/', include('Reseñas.urls')),
    path('Donaciones/', include('Donaciones.urls')),
    path('Estadisticas/', include('Estadisticas.urls')),
]

handler404 = admin_views.error404
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Noticias/urls.py
from django.urls import path
from . import views

app_name='Noticias'

urlpatterns=[
    path('agregar_noticia/', views.agregar_noticia,name="agregar_noticia"),
    path('delete_noticia/', views.delete_noticia,name="delete_noticia"),
    path('modify_noticia/', views.modify_noticia,name="modify_noticia"),
    path('set_noticia_id/', views.set_noticia_id, name="set_noticia_id"),
    ]

Pantalla_principal/urls.py
from django.urls import path
from . import views

app_name='Pantalla_principal' #esto es necesario para que dps cuando va a reest. contraseña o reg. usuario, siga el link apropiado

#urls que los clientes pueden visitar
urlpatterns = [
    path('', views.pantalla_principal,name="Pantalla_principal"),
    path('listar_notificaciones/', views.listar_notificaciones, name='listar_notificaciones'),
    path('delete_notificacion/', views.delete_notificacion, name='delete_notificacion'),
    path('donaciones/', views.donaciones,name="Donaciones"),
]

Pantalla_principal/models.py
from django.db import models
from accounts.models import Usuario

# Create your models here.
class Notificacion(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    mensaje = models.TextField()
    leida = models.BooleanField(default=False)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    borrado = models.BooleanField(default=False)

    def __str__(self):
        return f"Notificación para {self.usuario.username} - {self.mensaje[:20]}"

Pantalla_principal/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from Noticias.models import Noticia
from .models import Notificacion
from Noticias.models import Noticia

def pantalla_principal(request):
    noticias = Noticia.objects.filter(borrado = False).order_by('-fecha_creado')
    return render(request, 'indexPantalla_principal.html', {'noticias': noticias})

@login_required
def listar_notificaciones(request):
    notificaciones = Notificacion.objects.filter(usuario=request.user, borrado = False).order_by('-fecha_creacion')
    # Marcar las notificaciones como leídas
    notificaciones.update(leida=True)
    context = {
        'notificaciones': notificaciones
    }
    return render(request, 'listar_notificaciones.html', context)

@login_required
def donaciones(request):
    return render(request, 'indexDonaciones.html')

@login_required
def delete_notificacion(request):
    print("inside")
    if request.method == 'POST':
        notificacion_id = request.POST.get('notificacion_id')
        print(notificacion_id)
        if notificacion_id:
            notificacion = get_object_or_404(Notificacion, id=notificacion_id)
            notificacion.borrado = True
            notificacion.save()

    return redirect('Pantalla_principal:listar_notificaciones')

Pantalla_principal/templates/indexDonaciones.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="container">
    <div class="Articulos">
        <article>
            <h1> Donaciones </h1>
            <p> En proceso..... </p>
        </article>
    </div>
</div>


{% endblock %}

Pantalla_principal/templates/indexPantalla_principal.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% csrf_token %}
<link rel="stylesheet" href="{% static 'styles/mainPantalla_principal.css' %}">
<link rel="stylesheet" href="{% static 'styles/mainPantalla_principal.css' %}">
<div class="container">
    {% if user.is_authenticated %}
        {% if user.id == 1 %}
            <a href="{% url 'Noticias:agregar_noticia' %}" class="add-noticia-link">Agregar Noticia</a>
        {% endif %}
    {% endif %}
    <ul>
    {% if noticias %}
    {% for noticia in noticias %}
        <div class="Articulos">
            <article>
                <li>
                    <time>{{ noticia.fecha_creado|date:"d M Y H:i"}}</time>
                    <h1>{{ noticia.titulo }}</h1>
                    <p>{{ noticia.descripcion }}</p>
                    <img src="{{ noticia.foto.url }}" alt="Foto de {{ noticia.titulo }}">
                    {% if user.is_authenticated %}
                        {% if user.id == 1 %}
                            <form method="post" action="{% url 'Noticias:delete_noticia' %}" style="display:inline;" onsubmit="confirmDeletion(event)">
                                {% csrf_token %}
                                <input type="hidden" name="noticia_id" value="{{ noticia.id }}">
                                <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
                            </form>
                            <form method="post" action="{% url 'Noticias:set_noticia_id' %}" style="display:inline;">
                                {% csrf_token %}
                                <input type="hidden" name="noticia_id" value="{{ noticia.id }}">
                                <button type="submit" class="btn btn-primary btn-sm">Modificar</button>
                            </form>
                        {% endif %}
                    {% endif %}
                </li>
            </article>
        </div>
    {% endfor %}
    {% else %}
        <p>No hay noticias disponibles en este momento.</p>
    {% endif %}
<script>
    function confirmDeletion(event) {
        event.preventDefault();
        if (confirm("¿Estás seguro de que deseas eliminar esta noticia?")) {
            event.target.submit();
        }
    }
</script>

{% endblock %}

Pantalla_principal/templates/listar_notificaciones.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'styles/mainNotificaciones.css' %}">
<h2>Notificaciones</h2>
<div class="container">
    <ul>
        {% for notificacion in notificaciones %}
        <div class="Articulos">
            <time>{{ notificacion.fecha_creacion|date:"d M Y H:i" }}</time>
            {{ notificacion.mensaje }} 
            <form method="post" action="{% url 'Pantalla_principal:delete_notificacion' %}" class="delete-form">
                {% csrf_token %}
                <input type="hidden" name="notificacion_id" value="{{ notificacion.id }}">
                <button type="submit" class="delete-button">
                    <img id="Eliminar" src="{% static 'basura.png' %}" alt="Eliminar" class="delete-icon">
                </button>
            </form>
        </div>
        {% empty %}
            <li>No tienes notificaciones.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}